name: Publish to PyPI

on:
  push:
    branches: [ "hatch" ] #main can be added 
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Ensure this permission is available for trusted publishing

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install hatch
      - name: Build package
        run: hatch build
      - name: Test package
        run: hatch -e test run nose2 --verbose
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          #password: ${{ secrets.PYPI_API_TOKEN }}  # Ensure your PyPI API token is set in secrets otherwise trusted publishers mode 
          repository-url: https://test.pypi.org/legacy/  # Use Test PyPI or main PyPI https://upload.pypi.org/legacy/ 
